# Simulation-wide parameters 
#
sim.numSimulations = 3
sim.numSimulations.From = 11
sim.numSimulations.To = 15
sim.maxNodes = 10
sim.maxTransactions = 100000
sim.terminate.atTime = 1007200000
sim.output.directory = ./examples/results
sim.experimentalLabel = faithful.10node.30sim.11-15

# Reporter parameters 
#
reporter.reportEvents = true
reporter.reportTransactions = true
reporter.reportNodes = true
reporter.reportNetEvents = true
reporter.reportBeliefs = false
reporter.reportBeliefsShort = true

reporter.reportBlockEvents = true
reporter.reportStructureEvents = false

reporter.beliefReportInterval = 1000
reporter.beliefReportOffset = 3600000

reporter.reportingWindow = 100000


#Network-specific parameters
#
# net.sampler.file = ./src/main/resources/net.csv
net.sampler.seed = 123
net.sampler.seed.updateSeed = false
net.numOfNodes = 10
net.numOfHonestNodes = 10
net.numOfMaliciousNodes = 0
net.throughputMean = 25000000f
net.throughputSD = 2500000f
net.propagationTime = 10


# Workload Parameters
#
workload.sampler.file = ./examples/configs/faithful/bitcoin.faithful-workload.csv
workload.sampler.seed = 321
workload.sampler.seed.updateSeed = true
workload.lambda = 6.494f
#workload.numTransactions = 23378
workload.numTransactions = 70135
workload.sampleTransaction = {200, 210, 220, 230, 240, 250, 260, 270, 280, 290}
workload.txSizeMean = 225f
workload.txSizeSD = 120.9471f
workload.txFeeValueMean = 3619.23f
workload.txFeeValueSD = 369.19f


# Node Parameters
#
# node.sampler.file = ./src/main/resources/nodelist.csv
node.sampler.seed = {444,222}
node.sampler.updateSeedFlags = {false,true}
node.sampler.seedUpdateTimes = {49090}
node.createMaliciousNode = false
node.electricPowerMean = 1375f
node.electricPowerSD = 20f
node.electricCostMean = 0.1f
node.electricCostSD = 0.05f

# Hashpower Related
pow.difficulty = 4.3933890848757156E23
pow.hashPowerMean = 8.5934001000E10
pow.hashPowerSD = 8.5934001000E9


#
#
# Protocol-Specific Parameters
#
#

# Blockchain Specific Parameters
#
bitcoin.maxBlockSize = 1000000
bitcoin.minSizeToMine = 1000
bitcoin.minValueToMine = 1
# sampler.useFileBasedSampler = false
