---
title: "CNS: Finality analysis under limited block size."
author: "Anonymous"
format:
  gfm:
    toc: true
editor_options: 
  chunk_output_type: console
---

```{R echo = FALSE, warning=FALSE, message=FALSE}
# Knitr settings
knitr::opts_chunk$set(
  warning = FALSE,
  message = FALSE
)
```

# Preamble

## Reproduction

  
```{R warning=FALSE, message=FALSE}
# Main Parameters
logAnalysisToolPath = "../../../../cns-tools/R-Tools/src/logAnalysis/"

#Libraries
source(paste0(logAnalysisToolPath,"library.R"))

repo = "for-review-purposes"
toolsRepo = paste0("https://github.com/", repo,"/cns-tools")
bitcoinRepo = paste0("https://github.com/", repo,"/cns-bitcoin")

toBitRepo <- function(x) {
  return(paste0(bitcoinRepo,x))
}
```
  
- This document can be reproduced from preexisting data via "knitting" `r toBitRepo("/blob/main/examples/configs/size/blockSize.qmd")` that exists in the same directory. Steps need to be taken for the data to be generated or acquired - see below.
- The analysis requires R-based logAnalysis tools that can be cloned from `r toolsRepo`
- The variable `logAnalysisToolPath` needs to be set to the directory of
  `logAnalysis` scripts within your local clone of the `cns-tools` repo.
  

## Data Acquisition
- For this experiment data are not available within the repository (files too large).
- To regenerate data run instances of: `mvn exec:java -Dexec.args='-c ./examples/configs/size/size-factor.properties'` in which the parameter `bitcoin.maxBlockSize` is set respectively to values `r format(c(35000,45000,seq(30000,90000,by = 10000)), scientific = FALSE)` and all else is held as is.
- To use pre-generated please download from [this link](https://drive.proton.me/urls/T9W1AJHZMM#zpdimOQe0GmF) or user this user-friendly URL: [https://tinyurl.com/ccs2026-1065-blocksize](https://tinyurl.com/ccs2026-1065-blocksize). Then unzip all the files of the form `size-factor - XXX - YYYYY` inside `examples/results/`, where `XXX` is the workload size (different for each analysis) and `YYYYY` is the block size. 


# Overview

We investigate the role of block size to the finality and time-to-finality of individual transactions. We specifically consider the flow of incoming transactions and it terms of size in bytes (inflow) to the flow of block validations again in terms of size in bytes (outflow). In general, if the former is greater than the latter, competition for placement in blocks ensues, making finality and time-to-finality contingent on the transaction fees. We hence expect that, as we reduce block size, the point at which inflow equals outflow constitutes an inflection point, below which all transactions will enjoy a nominal finality rate, but beyond which, if we further reduce block size, low-fee transactions will experience increasingly longer time-to-finality scores. We hence devise an experimental set-up to investigate this qualitatively via graphing the corresponding data. 

We construct a network of $30$ nodes, and difficulty and node power at $4.4\cdot 10^{23}$ and $5.7\cdot 10^{10} GH$ which implies an expected block pace of about 4:15 minutes (mm:ss). We set end-to-end network connections to $25MB$ which allows broadcasting within seconds and prevents synchronization from becoming a nuisance factor. The rate of incoming transactions is set to $\lambda = 0.025$, i.e. $1.5$ transactions per minute and their average size is set to $10kB$. From these configurations it follows that inflow $\lambda * 10kB * 60 = 15kB/min$. The block size needed for serving this inflow needs to be such that inflow = outflow, hence, $\mathrm{(block size)}/\mathrm{(pace)} = 15kB$, which is satisfied for block size of about $64kB$. We run $100$ experiments for different block sizes around this point, starting from $90kB$ and reducing it to $30kB$. We use the same 100-arrivals workload with sample transactions 10, 20, 30, 40, 50, which are respectively the 10th, 20th, etc. transaction to arrive to the network out of the 100 that arrive. We set the size of these transactions specifically to be $10kB$ (others are normally distributed around that mean and a standard deviation of $1kB$) and set the fee associated with them to be respectively, the 10th, 25th, 50th, 75th, and 90th percentile of a normal distribution of fee levels with mean $3619.23$ and standard deviation $369.19$.

Below are the corresponding values that can also be found in `size-factor.csv`

```{R }
mean_val = 3619.23
sd_val = 3619.23/10

qnorm(c(0.1,0.25,0.5,0.75,0.90), mean = mean_val, sd = sd_val)
```

# Analysis

Variable `logAnalysisToolPath` must point to the `cns-tools/R-Tools/src/logAnalysis/` directory of `cns-tools`.


## Analysis Routines

Variable `outputFolder` must point to the directory where the output of the form `size-factor - XXX - YYYYY` is. Not included in this repo due to large size. Please refer to publication for pointers to data. Alternatively reproduce the data with CNS and rename files and directories as above, where `XXX` is the workload size (100 and 300), and `YYYYY` is the block size. Block sizes attempted are:

```{R echo = FALSE}
c(35000,45000,seq(30000,90000,by = 10000))
```


```{R echo = FALSE, warning=FALSE, message=FALSE}

analyzeExperiment <- function(experiment,bsize) {
  #Output folder
  outputFolder = "../../results/blockSize/"

  # Other Parameters
  txVector = c(10,20,30,40,50)

  # Data Read
  df <- setVars(outputFolder,experiment, txVector)
  
  producePaceData(outputFolder, experiment)

  pacedata = read_csv(paste0(outputFolder,experiment,
                            "/PaceData - ",experiment,".csv"))

  pace = pacedata %>%
    arrange(SimID, SimDiff) %>%             # ensure ordered
    summarise(
      `Block Time (mins) - Mean....:` = mean(SimDiff)/60000,
      `Block Time (mins) - St. Dev.:`   = sd(SimDiff)/60000
    )

  df$finalityData = getFinality(df$beliefData,
                                alignTimes = TRUE, 
                                threshold = 0.9,
                                arrivalTimes = 
                                  getTxArrivalTimes(df$inputData,txVector),
                                horizon = "2:40:00.000")

  finality.result = df$finalityData %>%
    select(Transaction,trials,successes,starts_with("threstest"),
           point_estimate,ci_low,ci_high)
  
  
  graph.data <- prepareGraphData(df$beliefData,
                                alignTimes = TRUE,
                                VaR = FALSE,
                                arrivalTimes =
                                  getTxArrivalTimes(df$inputData,txVector))

  time.to.finality <- getTimeToFinality(graph.data,threshold = 0.9) 
  
  return (list(pace = pace, finality.result = finality.result,graph.data = graph.data, time.to.finality = time.to.finality))
  
}


initializeStores <- function() {
  paces <<- tibble(`Block Time (mins) - Mean....:` = double(),
               `Block Time (mins) - St. Dev.:` = double(),
               experiment = character(),
               bsize = double())

  finalities <<- tibble(Transaction = double(),
                point_estimate = double(),
               experiment = character(),
               bsize = double())

  graph.data.result <<- tibble(Time = double(),
                           Transaction = factor(),
                           avgConf =double(),
                           sdConf = double(),
                           medConf = double(),
                           experiment = character(),
                           bsize = double())

  time.to.finalities <<- tibble(Transaction = factor(),
                             TimeFinalized = double(),
                             TimeFinalizedFrmt = character(),
                             experiment = character(),
                             bsize= double())
}
```


## Finalities

Below we analyze 100 experimental runs for a number of different block sizes ranging from $30Kb$ to $90Kb$. Workload is a total of 300 transactions. Finality is evaluated with horizon of 2 hours and 40 minutes, which is approximately the expected interval between the arrival of the last sample transaction (50) and the last transaction of the workload , past which there are unnaturally no more arrivals and nodes validate old left-over transactions. 

### Gather Data
```{R }
#| results: 'hide'

block_sizes = c(35000,45000,seq(30000,90000,by = 10000))

finalityRuns = paste0("size-factor - 300 - ",block_sizes)

initializeStores()

for (i in 1:length(finalityRuns)) {
  run = finalityRuns[i]
  block_size = block_sizes[i]
  
  x = analyzeExperiment(run,block_size)

  paces = bind_rows(paces,x$pace %>% mutate(experiment = run,
                                            bsize =block_size))

  finalities = bind_rows(finalities,x$finality.result %>%
                           select(Transaction,point_estimate) %>%
                           mutate(experiment = run,
                                  bsize =block_size))
  
  graph.data.result = bind_rows(graph.data.result,
                                x$graph.data %>%
                           mutate(experiment = run,
                                  bsize =block_size))

  time.to.finalities = bind_rows(time.to.finalities, x$time.to.finality %>%
                           mutate(experiment = run,
                                  bsize =block_size))
}
```


### Graph per Block Size

In the graph below $63kB$ is the block size at which the incoming flow in transaction bytes/sec, calculated by average transaction size and arrival rate, equals to outgoing flow (bytes validated per second), calculated based on block size and validation pace.

```{R }
finalityGraph.1 <- ggplot(data = 
         finalities %>% mutate(Transaction = as.factor(Transaction)),
       aes(x = bsize, y=point_estimate, color = Transaction)) + 
  geom_line() + 
  scale_x_reverse(expand = c(0.01,0),labels = function(x) paste0(x / 1000, " kB")) +
      geom_vline(xintercept = 63906, linetype = "dashed") +
    annotate("text", y = 0, x = +40000, label = "in rate > out rate\n(bytes/sec)    ",hjust = 1.1, vjust = -0.5) + 
    annotate("rect",
           xmin = 63906, xmax = -Inf,
           ymin = -Inf, ymax = Inf, fill = "yellow",
           alpha = 0.2) +
      labs(title = "Finality over Block Size",
           y = "Finality within h = 2:40:00",
           x = "Block Size (kilobytes)") +
  theme(
    axis.title.x = element_text(size = 14),
    axis.title.y = element_text(size = 14),
    axis.text.x = element_text(size = 12),
    axis.text.y = element_text(size = 12),
    plot.title = element_text(size = 15, face = "bold")
    #legend.position = "bottom"
  )


```

```{R echo = FALSE}
#| fig-cap: "Transaction finality vs. Block Size"
#| fig-width: 8
#| fig-height: 5.5

print(finalityGraph.1)
```


### Individual Graphs

In the graph below the progression of belief in the two extreme block sizes tried is seen.

```{R }
#| results: 'hide'
threshold = 0.9

b30 <- getBeliefGraph(graph.data.result %>% filter(bsize == 30000), xlim = c("0:00","1:00:00"),titleSuffix = ": 30kB Block") +
  theme(
    axis.title.x = element_text(size = 14),
    axis.title.y = element_text(size = 14),
    axis.text.x = element_text(size = 12),
    axis.text.y = element_text(size = 12),
    legend.position = "bottom") +
  geom_hline(yintercept = threshold, linetype = "dashed") + 
        annotate(
      "text",
      x = 0,
      y = threshold,
      label = "0.9",
      vjust = -0.5,
      hjust = 0,                  # flush left
      color = "darkred"
    )
b90 <- getBeliefGraph(graph.data.result %>% filter(bsize == 90000), xlim = c("0:00","1:00:00"),titleSuffix = ": 90kB Block") +
  theme(
    axis.title.x = element_text(size = 14),
    axis.title.y = element_text(size = 14),
    axis.text.x = element_text(size = 12),
    axis.text.y = element_text(size = 12),
    legend.position = "bottom") +
  geom_hline(yintercept = threshold, linetype = "dashed") + 
        annotate(
      "text",
      x = 0,
      y = threshold,
      label = "0.9",
      vjust = -0.5,
      hjust = 0,                  # flush left
      color = "darkred"
    ) 

```

```{R }
#| fig-cap: "Belief Progression Graphs under 30k vs 90k blocks"
#| fig-width: 8
#| fig-height: 5

grid.arrange(b30,b90,nrow = 1)
```


## Time to Finality

We now run the same experiment for 100 incoming transactions (instead of 300) and set the horizon to be the end of the simulation, such that all transactions are validated. The time to finality is then measured. 

### Gather Data
```{R }
#| results: 'hide'

block_sizes = c(35000,45000,55000,seq(30000,90000,by = 10000))

finalityRuns = paste0("size-factor - 100 - ",block_sizes)

initializeStores()

for (i in 1:length(finalityRuns)) {
  run = finalityRuns[i]
  block_size = block_sizes[i]
  
  x = analyzeExperiment(run,block_size)

  paces = bind_rows(paces,x$pace %>% mutate(experiment = run,
                                            bsize =block_size))

  finalities = bind_rows(finalities,x$finality.result %>%
                           select(Transaction,point_estimate) %>%
                           mutate(experiment = run,
                                  bsize =block_size))
  
  graph.data.result = bind_rows(graph.data.result,
                                x$graph.data %>%
                           mutate(experiment = run,
                                  bsize =block_size))

  time.to.finalities = bind_rows(time.to.finalities, x$time.to.finality %>%
                           mutate(experiment = run,
                                  bsize =block_size))
}
```




### Graph per block size

```{R }
# Function to convert minutes -> hh:mm:ss
minutes_to_hms <- function(mins) {
  h <- floor(mins / 60)
  m <- floor(mins %% 60)
  s <- round((mins - floor(mins)) * 60)
  sprintf("%02d:%02d:%02d", h, m, s)
}


timeToFinalityGraph <- ggplot(data = time.to.finalities, aes(x = bsize, y=TimeFinalized/60000, color = Transaction)) + 
      geom_line() + scale_x_reverse(expand = c(0.01,0),
                                     labels = function(x) paste0(x / 1000, " kB")) +
      geom_vline(xintercept = 63906, linetype = "dashed") +
      geom_hline(yintercept = 4217832/60000, linetype = "dashed") +
    annotate("text", y = 40, x = +73000, label = "workload ends\n(01:10:18)",hjust = 1, vjust = -0.5) + 
    annotate("text", y = 300, x = +40000, label = "in rate > out rate\n(bytes/sec)    ",hjust = 1, vjust = -0.5) + 
    annotate("rect",
           xmin = 63906, xmax = -Inf,
           ymin = -Inf, ymax = Inf, fill = "yellow",
           alpha = 0.2) +
  scale_y_continuous(labels = minutes_to_hms) +
      labs(title = "Time to Finality over Block Size",
           y = "Time (hh:mm:ss)",
           x = "Block Size (kilobytes)") +
  theme(
    axis.title.x = element_text(size = 14),
    axis.title.y = element_text(size = 14),
    axis.text.x = element_text(size = 12),
    axis.text.y = element_text(size = 12),
    plot.title = element_text(size = 15, face = "bold")
    #legend.position = "bottom"
  )
```


```{R echo = FALSE}
print(timeToFinalityGraph)
```


