# Simulation-wide parameters 
#
sim.numSimulations = 30
sim.numSimulations.From = 1
sim.numSimulations.To = 100
sim.maxNodes = 30
sim.maxTransactions = 1500
sim.terminate.atTime = 1007200000
sim.output.directory = ./examples/results

# Reporter parameters 
#
reporter.reportEvents = true
reporter.events.containerValidation = true
reporter.events.containerArrival = true
reporter.events.newTransactionArrival = true
reporter.events.seedUpdate = true

reporter.reportTransactions = true
reporter.reportNodes = true
reporter.reportNetEvents = true
reporter.reportBeliefs = false
reporter.reportBeliefsShort = true

reporter.reportBlockEvents = true
reporter.reportStructureEvents = true

reporter.beliefReportInterval = 1000
reporter.beliefReportOffset = 3600000

reporter.reportingWindow = 100000


#Network-specific parameters
#
# net.sampler.file = ./src/main/resources/net.csv
net.sampler.seed = 123
net.sampler.seed.updateSeed = false
net.numOfNodes = 30
net.numOfHonestNodes = 30
net.numOfMaliciousNodes = 0
net.throughputMean = 25000000f
net.throughputSD = 2500000f
net.propagationTime = 10


# Workload Parameters
#
workload.sampler.file = ./examples/configs/size/size-factor.csv
workload.sampler.seed = 321
workload.sampler.seed.updateSeed = true
workload.lambda = 0.025f
workload.numTransactions = 300
workload.sampleTransaction = {10,20,30,40,50}
workload.txSizeMean = 10000f
workload.txSizeSD = 100f
workload.txFeeValueMean = 3619.23f
workload.txFeeValueSD = 369.19f

workload.hasConflicts = false
workload.conflicts.likelihood = 0.01
workload.conflicts.dispersion = 0.5

workload.hasDependencies = false
workload.dependencies.dispersion = 0.5
workload.dependencies.mandatory = true
workload.dependencies.countMean = 1
workload.dependencies.countSD = 3


# Node Parameters
#
# node.sampler.file = ./src/main/resources/nodelist.csv
node.sampler.seed = {444,222}
node.sampler.updateSeedFlags = {true,true}
node.sampler.seedUpdateTimes = {350586}
node.createMaliciousNode = false
node.electricPowerMean = 1375f
node.electricPowerSD = 20f
node.electricCostMean = 0.1f
node.electricCostSD = 0.05f

# Hashpower Related
pow.difficulty = 4.3933890848757156E23
pow.hashPowerMean = 5.72893340E+10
pow.hashPowerSD = 5.72893340E+9



#
#
# Protocol-Specific Parameters
#
#

# Bitcoin Specific Parameters
#
bitcoin.maxBlockSize = 30000
bitcoin.minSizeToMine = 100
bitcoin.minValueToMine = 1

